### ISSUE TITLE
hardcoded params

### ISSUE THREAD

**Issue by sba5827** [InstituteforDiseaseModeling/synthpops#57]
https://github.com/InstituteforDiseaseModeling/synthpops/blob/f5272df682f09635a25d7a1830050b1229102e6a/synthpops/api.py#L83-L86

would be better to have this as function params with default values

**Comment by cliffckerr** [comment]
Thanks @sba5827 -- this is fixed in the new version just released, which also moves to a class-based paradigm:
https://github.com/InstituteforDiseaseModeling/synthpops/blob/master/synthpops/pop.py#L23
Note that this is very much a work in progress, and we're redoing the data input system to use a database instead of files over the next few weeks.

**Comment by dinacmistry** [comment]
Closing this as synthpops now uses default location parameters but has the ability for users to specify other locations (so long as the data json exists! checkout the changelog for more details).
